### ISSUE TITLE
can add end date greater than start date in Edit Professional Experience also selected file is not coming in edit , add char limit

### ISSUE THREAD

**Issue by MaroofTech** [Anupriyabanger/Bee-Recruiter#1808]
![Screenshot from 2023-12-27 18-39-28](https://github.com/Anupriyabanger/Bee-Recruiter/assets/78342064/6e343010-c6eb-42cf-961c-918ea3f3cb68)
![Screenshot from 2023-12-28 10-57-27](https://github.com/Anupriyabanger/Bee-Recruiter/assets/78342064/5710a189-daec-4ac3-b07a-f3239c1d8633)

**Comment by MaroofTech** [comment]
Still no option to view selected file
![Screenshot from 2023-12-29 11-38-16](https://github.com/Anupriyabanger/Bee-Recruiter/assets/78342064/07599758-5f93-4b91-91d6-56b5525d5693)

**Comment by MaroofTech** [comment]
Filled all fields but still bitton is diasbale
![Screenshot from 2024-01-03 13-36-04](https://github.com/Anupriyabanger/Bee-Recruiter/assets/78342064/d70a2587-9f3c-4e57-bc81-3340766aca51)

**Comment by pankajVayuz** [comment]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/124441177/642b6695-6328-4129-8201-b4effb848d41)

this issue is fixed

**Comment by MaroofTech** [comment]
currently working not checked also i submitted form with previously coming images and its not coming 

![Screenshot from 2024-01-04 17-38-24](https://github.com/Anupriyabanger/Bee-Recruiter/assets/78342064/48edb5a7-f01f-4676-b7c2-70084512e242)

![Screenshot from 2024-01-04 17-40-12](https://github.com/Anupriyabanger/Bee-Recruiter/assets/78342064/a29c0926-76a4-4e07-8d7c-2cac9fe2dabe)

**Comment by MaroofTech** [comment]
Still not working @SaurabhattJi 
![Screenshot from 2024-01-08 16-56-58](https://github.com/Anupriyabanger/Bee-Recruiter/assets/78342064/89ea39db-712b-4d63-b8f8-b4c50cd37e39)
![Screenshot from 2024-01-08 16-56-37](https://github.com/Anupriyabanger/Bee-Recruiter/assets/78342064/0faf02c8-e8fd-4ac6-bbff-516a39ba8422)

**Comment by SaurabhattJi** [comment]
Now managed from state also.

**Comment by rajasrivastava101** [comment]
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/129847373/9eadcb24-2c85-47da-8953-0036479a6256)
I mention the previous date, but I don't see any errors. There should be an error in mentioning the previous date in the end date for the professional experience.
