### ISSUE TITLE
Web > Job Seeker > UI > Homepage

### ISSUE THREAD

**Issue by milivayuz** [Anupriyabanger/Bee-Recruiter#2341]
<img width="959" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/156641922/eb2ba066-95a1-4e38-bac1-897d5420e204">

Different card size

**Comment by vinayak-vayuz** [comment]
<img width="960" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/95282ec5-7fe3-45f3-b2e8-ba30147ac223">
Done

**Comment by milivayuz** [comment]
<img width="747" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/156641922/fa6e16fb-114a-4b2a-9514-15ad9533005a">

Issue is still there

**Comment by vinayak-vayuz** [comment]
<img width="960" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/d9aa959e-2df2-4687-ac4d-30ef9cb1682b">

**Comment by milivayuz** [comment]
<img width="959" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/156641922/10277569-e3db-4271-bc47-118c89b6acac">

Still different

**Comment by vinayak-vayuz** [comment]
<img width="838" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/128778447/950d0c62-fda9-43c4-b014-1ea129018738">

**Comment by milivayuz** [comment]
<img width="398" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/156641922/486cad01-5aab-43d5-8454-e72b32f651ff">

remove select currency and select rate
