### ISSUE TITLE
App > Consultant > UI > Post Job

### ISSUE THREAD

**Issue by milivayuz** [Anupriyabanger/Bee-Recruiter#2717]
<img width="117" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/156641922/7c5e1b9b-22fb-44e8-8b89-2a6642e1d6b1">
Add icons in all the boxes

**Comment by rajasrivastava101** [comment]
Not all fields have icons. Implement it in every field.

**Comment by kaviraj-thakurr** [comment]
fixed
![1000409273](https://github.com/Anupriyabanger/Bee-Recruiter/assets/152268279/489e80bb-f50f-4b96-a60f-af5985dfa29c)

**Comment by milivayuz** [comment]
<img width="152" alt="image" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/156641922/6d306f31-d30d-449f-a102-9c632dbbb3ac">
still not there
